development:
  adapter: postgresql
  encoding: utf8
  database: article-lounge-two_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: article-lounge-two_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: article-lounge-two_production
  pool: 5
  username:
  password:

cucumber:
  <<: *TEST
