development:
  adapter: postgresql
  database: article-lounge-two_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: article-lounge-two_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: article-lounge-two_production
  pool: 5
  timeout: 5000
